[package]
name = "dirback_gui"
version = "0.1.0"
description = "GUI for the dirback"
edition.workspace = true

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "dirback_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
dirback.workspace = true

anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

[build-dependencies]
mktemp.workspace = true

tauri-build = { version = "2", features = [] }
