[package]
name = "dirback_cmd"
description = "Dirback commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
dirback.workspace = true

anyhow = { workspace = true }

[dev-dependencies]
mktemp.workspace = true
