[package]
name = "dirback"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = "0.4.40"
directories = "6.0.0"
thiserror = { workspace = true }
uuid = { version = "1.16.0", features = ["v4"] }

