[package]
name = "dirback_tui"
version = "0.1.0"
edition.workspace = true

[dependencies]
dirback.workspace = true

anyhow = { workspace = true }
crossterm = "0.28.1"
ratatui = "0.29.0"

[dev-dependencies]
mktemp.workspace = true
